# Generated by Django 5.2.12 on 2026-03-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status do Livro'),
        ),
    ]
